### ISSUE TITLE
Adobe 2021 issue The value returned from the handleResponseObject function is not of type binary.

### ISSUE THREAD

**Issue by alorne** [inLeagueLLC/wkhtmltopdf#4]
This one may be a little beyond me, I don't deal with a lot of binary.

modules/wkhtmltopdf/models/PDFService.cfc: 46: ` return handleResponseObject( response = local.pdfResponse );`

If the component name is specified as a return type, it is possible that either a definition file for the component cannot be found or is not accessible.

Slack trace below:

coldfusion.runtime.UDFMethod$InvalidReturnTypeException( The value returned from the handleResponseObject function is not of type binary.
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:577)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:516)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:463)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:438)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:681)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4909)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4890)
    at cfPDFService2ecfc153512975$funcTOPDF.runFunction(/app/modules/wkhtmltopdf/models/PDFService.cfc:46)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:623)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:553)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:516)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:463)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:438)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:681)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:980)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:762)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:4165)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:4129)
    at cfsales2ecfc759538788$funcDOCUMENT.runFunction(/app/handlers/sales.cfc:1120)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:623)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:516)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:463)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:438)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:681)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:980)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:762)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:4165)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:4129)
    at coldfusion.runtime.CFPage.invoke(CFPage.java:16847)
    at cfController2ecfc102072789$funcINVOKER.runFunction(/app/coldbox/system/web/Controller.cfc:1197)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:623)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:516)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:463)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:438)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:681)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4909)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4890)
    at cfController2ecfc102072789$func_RUNEVENT.runFunction(/app/coldbox/system/web/Controller.cfc:948)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:623)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:516)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:463)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:438)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:681)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4909)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4890)
    at cfController2ecfc102072789$funcRUNEVENT.runFunction(/app/coldbox/system/web/Controller.cfc:658)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:623)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:516)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:463)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:438)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:681)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:980)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:762)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:4165)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:4129)
    at cfbootstrap2ecfc966209899$funcPROCESSCOLDBOXREQUEST.runFunction(/app/coldbox/system/bootstrap.cfc:290)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:623)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:516)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:463)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:438)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:310)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:5011)
    at coldfusion.runtime.CfJspPage._invokeUDF(CfJspPage.java:4991)
    at cfbootstrap2ecfc966209899$funcONREQUESTSTART.runFunction(/app/coldbox/system/bootstrap.cfc:507)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:623)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:553)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:516)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:463)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:438)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:310)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:975)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:696)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:503)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:4254)
    at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:4217)
    at cfApplication2ecfc1572209739$funcONREQUESTSTART.runFunction(/app/Application.cfc:37)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:623)
    at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:553)
    at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:516)
    at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:463)
    at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:438)
    at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:310)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:975)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:696)
    at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:503)
    at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:115)
    at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:286)
    at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:562)
    at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:43)
    at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
    at coldfusion.filter.PathFilter.invoke(PathFilter.java:162)
    at coldfusion.filter.IpFilter.invoke(IpFilter.java:45)
    at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:97)
    at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:81)
    at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
    at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
    at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
    at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
    at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
    at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
    at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:151)
    at coldfusion.CfmServlet.service(CfmServlet.java:231)
    at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:311)
    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
    at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47)
    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
    at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
    at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:257)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:182)
    at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImpl(RequestDispatcherImpl.java:225)
    at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImplSetup(RequestDispatcherImpl.java:147)
    at io.undertow.servlet.spec.RequestDispatcherImpl.forward(RequestDispatcherImpl.java:110)
    at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:45)
    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
    at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
    at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:257)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:182)
    at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImpl(RequestDispatcherImpl.java:225)
    at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImplSetup(RequestDispatcherImpl.java:147)
    at io.undertow.servlet.spec.RequestDispatcherImpl.forward(RequestDispatcherImpl.java:110)
    at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:215)
    at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
    at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
    at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
    at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:405)
    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
    at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
    at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
    at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
    at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
    at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
    at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
    at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
    at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
    at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
    at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
    at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
    at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
    at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
    at java.base/java.lang.Thread.run(Unknown Source)

**Comment by DiscountDarcy** [comment]
What happens if you remove the type definition from `handleResponseObject` so it's just `private function handleResponseObject(` ?

If the Hyper call to the web service succeeds, the response is going to be a binary object. Unless ACF handles the binary type differently somehow? If it works when you remove the type definition, we'll just do that. If not, whatever error it throws should tell us a bit more about what's going on.

You could also put in a `dump( arguments.response )` on the first line of the function to see what exactly ACF thinks is coming back from the web service.

**Comment by alorne** [comment]
Removing bianary broke the file that was downloaded. Below is the response from within the handleResponseObject.
![Screenshot 2022-06-23 092357](https://user-images.githubusercontent.com/14872635/175309538-f24da744-9b91-4723-8b68-4bf622adf360.png)

**Comment by DiscountDarcy** [comment]
What do you mean by 'broke the file that was downloaded'? What exactly happens?

**Comment by alorne** [comment]
![Screenshot 2022-06-23 101034](https://user-images.githubusercontent.com/14872635/175319973-6b7aa557-a399-4aad-a81e-8776483561e6.png)
When I open the PDF

**Comment by DiscountDarcy** [comment]
Assuming this is a problem with the file being returned, it is likely due to some difference between how the engines process the binary result.

I will have to set up an ACF testbed to get into this, which I should be able to do by next week.

**Comment by alorne** [comment]
I'll continue working on it and let you know if I find a solution. You are right about what is being returned being the issue. I had a solution last week, but I undid it while testing this stuff out and can't remember what it was.

Did you happen to update forgebox yet?

Thanks for all your help

**Comment by DiscountDarcy** [comment]
Further research:

The result from the Hyper call in Lucee is this:

![image](https://user-images.githubusercontent.com/11874518/176002980-da62eb46-257d-43dc-b618-2310d09b6071.png)

From Adobe it's (as you said) a ` java.io.ByteArrayOutputStream`

It needs `.toByteArray()` called on it.

The other issue is that the PDF request object was missing an actual content attribute, so it was returning 0 bytes. This will be fixed momentarily.

**Comment by DiscountDarcy** [comment]
Published v1.1.0 on Forgebox!

**Comment by alorne** [comment]
Awesome, thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
